# Generated by Django 3.2 on 2021-04-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('reference', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=3000)),
                ('terms', models.CharField(max_length=4000)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Sent', 'sent'), ('Declined', 'declined'), ('Accepted', 'accepted'), ('Invoiced', 'invoiced')], default='Draft', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('disc', models.DecimalField(decimal_places=4, default=None, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=None, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Create', 'create'), ('Edit', 'edit'), ('Sent', 'sent'), ('Quote viewed', 'quote viewed'), ('Message', 'message'), ('Note', 'note'), ('Accepted', 'accepted'), ('Invoiced', 'invoiced'), ('Copied', 'copied')], default='Create', max_length=64)),
                ('user', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=3000)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
            ],
        ),
    ]
