# Generated by Django 3.2 on 2021-04-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='number',
            new_name='quote_number',
        ),
    ]
