# Generated by Django 3.2 on 2021-04-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_number_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='terms',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='disc',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
