# Generated by Django 3.2 on 2021-05-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quoteitem_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
